version: '2'

# The default docker-compose.override file can use the "localhost" as the external name for testing web apps within the same dev machine. 
# The BEERSHOP_EXTERNAL_DNS_NAME_OR_IP environment variable is taken, by default, from the ".env" file defined like: 
#     BEERSHOP_EXTERNAL_DNS_NAME_OR_IP=localhost
# but values present in the environment vars at runtime will always override those defined inside the .env file
# An external IP or DNS name has to be used (instead localhost and the 10.0.75.1 IP) when testing the Web apps from remote machines/devices using the same WiFi, for instance.

services:

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5101
      - ConnectionString=Server=sql.data;Database=CatalogDb;User Id=sa;Password=Pass@word
      - ExternalCatalogBaseUrl=http://${BEERSHOP_EXTERNAL_DNS_NAME_OR_IP}:5101    #Local: You need to open your local dev-machine firewall at range 5100-5105.  at range 5100-5105.	  
      - EventBusConnection=rabbitmq
    ports:
      - "5101:5101"

  webmvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5100
      - CatalogUrl=http://catalog.api:5101
    ports:
      - "5100:5100"

  sql.data:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"

  webstatus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5107
      - CatalogUrl=http://catalog.api:5101/hc
      - mvc=http://webmvc:5100/hc
    ports:
      - "5107:5107"
