version: '2'

services:
  catalog.api:
    image: beershop/catalog.api
    build:
      context: ./src/Services/Catalog/Catalog.API
      dockerfile: Dockerfile
    depends_on:
      - sql.data
      - rabbitmq

  webmvc:
    image: beershop/webmvc
    build:
      context: ./src/Web/WebMVC
      dockerfile: Dockerfile
    depends_on:
      - catalog.api

  sql.data:
    image: microsoft/mssql-server-linux

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"

  webstatus:
    image: beershop/webstatus
    build:
      context: ./src/Web/WebStatus
      dockerfile: Dockerfile
